version: '2.1'
services:

  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  database-service:
    container_name: database-service
    env_file:
      - .env
    build: database-service
    ports:
      - 8081:8081

  identity-service:
    container_name: identity-service
    env_file:
      - .env
    build: identity-service
    ports:
      - 8082:8082

 # plane-service:
 #   container_name: plane-service
 #   env_file:
 #     - .env
 #   build: plane-service
 #   ports:
 #     - 8083:8083

 # gateway:
 #   container_name: gateway
 #   env_file:
 #     - .env
 #   build: gateway
 #   ports:
 #     - 8084:8084

volumes:
  postgres-data: